Add sniffer implementation for UDP and TCP packets
Megalotron/TheZAP pull request #1
Opened 2021-12-08 17:12 UTC by tocola

# Description

This PR adds a sniffer implementation for UDP and TCP packets, as well as the global architecture of TheZap stack.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [X] I have tested this code
- [X] I have added sufficient documentation in the code

# Additional comments

I have added network tools abstraction like packets and protocols

2021-12-08 17:46 UTC, PtitLuca reviewed
LGTM ! Take a look at my comment about the value returned by one of the sniffer's method and feel free to merge :rocket:

2021-12-08 17:46 UTC, PtitLuca commented on sniffer/src/sniffer.cpp
>  }
Could you return an optional object here ?

2021-12-08 18:27 UTC, Breigner01 requested changes

2021-12-08 18:27 UTC, Breigner01 commented on sniffer/include/sniffer.hpp
> +    std::vector<network::packet> m_packets;
brace initialization

2021-12-08 18:27 UTC, Breigner01 commented on sniffer/include/sniffer.hpp
> +    mutable std::mutex m_mtx;
brace initialization

2021-12-08 18:27 UTC, Breigner01 commented on sniffer/src/sniffer.cpp
> +        m_packets.push_back({protocol_map.at(typeid(T)), ip.src_addr().to_string(), ip.dst_addr().to_string(), protocol.sport(), protocol.dport(), get_payload(pdu)});
Elle me parait longue cette ligne

2021-12-09 13:10 UTC, tocola commented on .github/workflows/CI.yml
> +    branches: ["main", "master", "develop" ]
Fixed in  https://github.com/Megalotron/TheZAP/pull/1/commits/253fdbfd47f7995a24826587a2010045ac2cadde

2021-12-09 13:10 UTC, tocola commented on sniffer/include/sniffer.hpp
> +    std::vector<network::packet> m_packets;
Fixed in https://github.com/Megalotron/TheZAP/pull/1/commits/253fdbfd47f7995a24826587a2010045ac2cadde

2021-12-09 13:10 UTC, tocola commented on sniffer/src/sniffer.cpp
> +        m_packets.push_back({protocol_map.at(typeid(T)), ip.src_addr().to_string(), ip.dst_addr().to_string(), protocol.sport(), protocol.dport(), get_payload(pdu)});
Fixed in https://github.com/Megalotron/TheZAP/pull/1/commits/253fdbfd47f7995a24826587a2010045ac2cadde

2021-12-09 13:12 UTC, tocola commented on sniffer/src/sniffer.cpp
>  }
This will not be taken into account because adding an optional overload will result in more check in both sniffer and injector side

2021-12-09 13:57 UTC, PtitLuca approved these changes
LGTM !

2021-12-09 14:55 UTC, Breigner01 reviewed
LGTM

2021-12-09 14:55 UTC, Breigner01 approved these changes

2021-12-09 14:57 UTC, merged